# Basic `dependabot.yml` file with
# https://docs.github.com/zh/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#example-dependabotyml-file
# https://docs.github.com/zh/code-security/dependabot/working-with-dependabot/dependabot-options-reference#ignore

version: 2
updates:
  # npm 依赖版本更新
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"

  # GitHub Actions 版本更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
