# 工作流名称
name: Build-and-deploy
# run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  # 触发条件：当推送到 main 分支时
  push:
    branches: [main]
    # 以下文件的变更不会触发工作流
    paths-ignore:
      - "**.md"
      - "**.spec.js"
      - ".idea"
      - ".vscode"
      - ".dockerignore"
      - "Dockerfile"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/build.yml"

# 如果您不提供带有访问令牌或SSH密钥的操作，则必须访问您的存储库设置并将Read and Write Permissions提供给所提供的GITHUB_TOKEN，
# 否则可能会遇到权限问题。或者，您可以在工作流文件中设置以下内容，以授予操作所需的权限。https://github.com/JamesIves/github-pages-deploy-action
# 设置 GitHub Token 的权限
permissions:
  contents: write

jobs:
  # 第一个任务：构建发布文件
  build-release-files:
    # 指定运行环境
    runs-on: ${{ matrix.os }}

    # 设置矩阵策略，这里只使用 ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      # 步骤1：检出代码
      - name: Checkout Code
        uses: actions/checkout@v3

      # 步骤2：设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  

      # 步骤3：安装项目依赖
      - name: Install Dependencies
        run: npm install 

      # 步骤4：构建项目
      - name: Build Release Files
        run: npm run build
      
      # 步骤5：测试目录内容
      - name: Test
        run: ls
      
      # 步骤6：部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/

      # 以下是被注释掉的上传构建产物步骤
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build_on_${{ matrix.os }}
      #     path: dist/
      #     retention-days: 5
  
  # 第二个任务：部署到 GitHub
  deploy-on-github:
    # 依赖于 build-release-files 任务完成
    needs: build-release-files
    runs-on: ubuntu-latest

    steps:
      # 测试步骤
      - name: Test
        run: ls
      # 以下是被注释掉的部署步骤
      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: dist/

      # 默认是部署到 gh-pages 分支上，如果分支不存在会自动创建，可以在with下面添加branch参数来指定部署到哪个分支上
      # 在部署之前需要包含actions/checkout步骤