name: Build-and-deploy
# run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.spec.js"
      - ".idea"
      - ".vscode"
      - ".dockerignore"
      - "Dockerfile"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/build.yml"

jobs:
  build-release-files:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  

      - name: Install Dependencies
        run: npm install 

      - name: Build Release Files
        run: npm run build

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build_on_${{ matrix.os }}
      #     path: dist/
      #     retention-days: 5
  
  deploy-on-github:
    needs: build-release-files
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: ls
      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: dist/